package com.codeflow.domain.algorithm.airforce;

public enum Situation {
    NO_BOXES_ON_THE_RIGHT_AND_LEFT_SIDES,
    NO_BOXES_ON_THE_RIGHT_SIDE,
    NO_BOXES_ON_THE_LEFT_SIDE,
    THERE_ARE_BOXES_ON_BOTH_SIDES_AND_EQUAL,
    THERE_ARE_BOXES_ON_BOTH_SIDES_AND_NOT_EQUAL
}
